"""Change default language preference to Hebrew

Revision ID: 7836beeeab0f
Revises: 8c8015fe8d73
Create Date: 2025-08-28 02:47:54.986535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7836beeeab0f'
down_revision = '8c8015fe8d73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
