"""Add is_deactivated field to llm_providers

Revision ID: d5f8fe7c9d58
Revises: 7836beeeab0f
Create Date: 2025-09-11 15:15:38.583279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f8fe7c9d58'
down_revision = '7836beeeab0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('is_deactivated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_providers', 'is_deactivated')
    # ### end Alembic commands ###
