"""add profile_image_url to teacher and student profiles

Revision ID: a50018d10a57
Revises: add_conversation_state
Create Date: 2025-09-12 18:09:24.909466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50018d10a57'
down_revision = 'add_conversation_state'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('teacher_profiles', sa.Column('profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profiles', 'profile_image_url')
    op.drop_column('student_profiles', 'profile_image_url')
    # ### end Alembic commands ###
