"""Add TaskInteraction model for research analytics

Revision ID: 46615b93251d
Revises: 6b9ba09fe8f6
Create Date: 2025-08-27 17:17:35.339326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46615b93251d'
down_revision = '6b9ba09fe8f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.Enum('HELP_REQUEST', 'BREAKDOWN', 'EXAMPLE', 'EXPLANATION', 'FEEDBACK', name='interactiontype'), nullable=True),
    sa.Column('student_input', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('satisfaction_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_interactions_id'), 'task_interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_interactions_id'), table_name='task_interactions')
    op.drop_table('task_interactions')
    # ### end Alembic commands ###
